// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: cacheserver/v1/cacheserver.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_cacheserver_v1_cacheserver_proto protoreflect.FileDescriptor

const file_cacheserver_v1_cacheserver_proto_rawDesc = "" +
	"\n" +
	" cacheserver/v1/cacheserver.proto\x12\x0ecacheserver.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fcacheserver/v1/namespaced.proto\x1a\x1bcacheserver/v1/secret.proto2\xaf\x03\n" +
	"\vCacheServer\x12;\n" +
	"\x03Set\x12\x1a.cacheserver.v1.SetRequest\x1a\x16.google.protobuf.Empty\"\x00\x12;\n" +
	"\x03Del\x12\x1a.cacheserver.v1.DelRequest\x1a\x16.google.protobuf.Empty\"\x00\x12@\n" +
	"\x03Get\x12\x1a.cacheserver.v1.GetRequest\x1a\x1b.cacheserver.v1.GetResponse\"\x00\x12G\n" +
	"\tSetSecret\x12 .cacheserver.v1.SetSecretRequest\x1a\x16.google.protobuf.Empty\"\x00\x12G\n" +
	"\tDelSecret\x12 .cacheserver.v1.DelSecretRequest\x1a\x16.google.protobuf.Empty\"\x00\x12R\n" +
	"\tGetSecret\x12 .cacheserver.v1.GetSecretRequest\x1a!.cacheserver.v1.GetSecretResponse\"\x00B#Z!cacheserver/api/cacheserver/v1;v1b\x06proto3"

var file_cacheserver_v1_cacheserver_proto_goTypes = []any{
	(*SetRequest)(nil),        // 0: cacheserver.v1.SetRequest
	(*DelRequest)(nil),        // 1: cacheserver.v1.DelRequest
	(*GetRequest)(nil),        // 2: cacheserver.v1.GetRequest
	(*SetSecretRequest)(nil),  // 3: cacheserver.v1.SetSecretRequest
	(*DelSecretRequest)(nil),  // 4: cacheserver.v1.DelSecretRequest
	(*GetSecretRequest)(nil),  // 5: cacheserver.v1.GetSecretRequest
	(*emptypb.Empty)(nil),     // 6: google.protobuf.Empty
	(*GetResponse)(nil),       // 7: cacheserver.v1.GetResponse
	(*GetSecretResponse)(nil), // 8: cacheserver.v1.GetSecretResponse
}
var file_cacheserver_v1_cacheserver_proto_depIdxs = []int32{
	0, // 0: cacheserver.v1.CacheServer.Set:input_type -> cacheserver.v1.SetRequest
	1, // 1: cacheserver.v1.CacheServer.Del:input_type -> cacheserver.v1.DelRequest
	2, // 2: cacheserver.v1.CacheServer.Get:input_type -> cacheserver.v1.GetRequest
	3, // 3: cacheserver.v1.CacheServer.SetSecret:input_type -> cacheserver.v1.SetSecretRequest
	4, // 4: cacheserver.v1.CacheServer.DelSecret:input_type -> cacheserver.v1.DelSecretRequest
	5, // 5: cacheserver.v1.CacheServer.GetSecret:input_type -> cacheserver.v1.GetSecretRequest
	6, // 6: cacheserver.v1.CacheServer.Set:output_type -> google.protobuf.Empty
	6, // 7: cacheserver.v1.CacheServer.Del:output_type -> google.protobuf.Empty
	7, // 8: cacheserver.v1.CacheServer.Get:output_type -> cacheserver.v1.GetResponse
	6, // 9: cacheserver.v1.CacheServer.SetSecret:output_type -> google.protobuf.Empty
	6, // 10: cacheserver.v1.CacheServer.DelSecret:output_type -> google.protobuf.Empty
	8, // 11: cacheserver.v1.CacheServer.GetSecret:output_type -> cacheserver.v1.GetSecretResponse
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cacheserver_v1_cacheserver_proto_init() }
func file_cacheserver_v1_cacheserver_proto_init() {
	if File_cacheserver_v1_cacheserver_proto != nil {
		return
	}
	file_cacheserver_v1_namespaced_proto_init()
	file_cacheserver_v1_secret_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cacheserver_v1_cacheserver_proto_rawDesc), len(file_cacheserver_v1_cacheserver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cacheserver_v1_cacheserver_proto_goTypes,
		DependencyIndexes: file_cacheserver_v1_cacheserver_proto_depIdxs,
	}.Build()
	File_cacheserver_v1_cacheserver_proto = out.File
	file_cacheserver_v1_cacheserver_proto_goTypes = nil
	file_cacheserver_v1_cacheserver_proto_depIdxs = nil
}
