// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: cacheserver/v1/namespaced.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         *anypb.Any             `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Expire        *durationpb.Duration   `protobuf:"bytes,4,opt,name=expire,proto3,oneof" json:"expire,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	mi := &file_cacheserver_v1_namespaced_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cacheserver_v1_namespaced_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_cacheserver_v1_namespaced_proto_rawDescGZIP(), []int{0}
}

func (x *SetRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *SetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetRequest) GetValue() *anypb.Any {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *SetRequest) GetExpire() *durationpb.Duration {
	if x != nil {
		return x.Expire
	}
	return nil
}

type DelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelRequest) Reset() {
	*x = DelRequest{}
	mi := &file_cacheserver_v1_namespaced_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelRequest) ProtoMessage() {}

func (x *DelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cacheserver_v1_namespaced_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelRequest.ProtoReflect.Descriptor instead.
func (*DelRequest) Descriptor() ([]byte, []int) {
	return file_cacheserver_v1_namespaced_proto_rawDescGZIP(), []int{1}
}

func (x *DelRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *DelRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_cacheserver_v1_namespaced_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cacheserver_v1_namespaced_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_cacheserver_v1_namespaced_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *anypb.Any             `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Expire        *durationpb.Duration   `protobuf:"bytes,2,opt,name=expire,proto3" json:"expire,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_cacheserver_v1_namespaced_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cacheserver_v1_namespaced_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_cacheserver_v1_namespaced_proto_rawDescGZIP(), []int{3}
}

func (x *GetResponse) GetValue() *anypb.Any {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetResponse) GetExpire() *durationpb.Duration {
	if x != nil {
		return x.Expire
	}
	return nil
}

var File_cacheserver_v1_namespaced_proto protoreflect.FileDescriptor

const file_cacheserver_v1_namespaced_proto_rawDesc = "" +
	"\n" +
	"\x1fcacheserver/v1/namespaced.proto\x12\x0ecacheserver.v1\x1a\x19google/protobuf/any.proto\x1a\x1egoogle/protobuf/duration.proto\"\xab\x01\n" +
	"\n" +
	"SetRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\x05value\x126\n" +
	"\x06expire\x18\x04 \x01(\v2\x19.google.protobuf.DurationH\x00R\x06expire\x88\x01\x01B\t\n" +
	"\a_expire\"<\n" +
	"\n" +
	"DelRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"<\n" +
	"\n" +
	"GetRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"l\n" +
	"\vGetResponse\x12*\n" +
	"\x05value\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\x05value\x121\n" +
	"\x06expire\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x06expireB#Z!cacheserver/api/cacheserver/v1;v1b\x06proto3"

var (
	file_cacheserver_v1_namespaced_proto_rawDescOnce sync.Once
	file_cacheserver_v1_namespaced_proto_rawDescData []byte
)

func file_cacheserver_v1_namespaced_proto_rawDescGZIP() []byte {
	file_cacheserver_v1_namespaced_proto_rawDescOnce.Do(func() {
		file_cacheserver_v1_namespaced_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cacheserver_v1_namespaced_proto_rawDesc), len(file_cacheserver_v1_namespaced_proto_rawDesc)))
	})
	return file_cacheserver_v1_namespaced_proto_rawDescData
}

var file_cacheserver_v1_namespaced_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_cacheserver_v1_namespaced_proto_goTypes = []any{
	(*SetRequest)(nil),          // 0: cacheserver.v1.SetRequest
	(*DelRequest)(nil),          // 1: cacheserver.v1.DelRequest
	(*GetRequest)(nil),          // 2: cacheserver.v1.GetRequest
	(*GetResponse)(nil),         // 3: cacheserver.v1.GetResponse
	(*anypb.Any)(nil),           // 4: google.protobuf.Any
	(*durationpb.Duration)(nil), // 5: google.protobuf.Duration
}
var file_cacheserver_v1_namespaced_proto_depIdxs = []int32{
	4, // 0: cacheserver.v1.SetRequest.value:type_name -> google.protobuf.Any
	5, // 1: cacheserver.v1.SetRequest.expire:type_name -> google.protobuf.Duration
	4, // 2: cacheserver.v1.GetResponse.value:type_name -> google.protobuf.Any
	5, // 3: cacheserver.v1.GetResponse.expire:type_name -> google.protobuf.Duration
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_cacheserver_v1_namespaced_proto_init() }
func file_cacheserver_v1_namespaced_proto_init() {
	if File_cacheserver_v1_namespaced_proto != nil {
		return
	}
	file_cacheserver_v1_namespaced_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cacheserver_v1_namespaced_proto_rawDesc), len(file_cacheserver_v1_namespaced_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cacheserver_v1_namespaced_proto_goTypes,
		DependencyIndexes: file_cacheserver_v1_namespaced_proto_depIdxs,
		MessageInfos:      file_cacheserver_v1_namespaced_proto_msgTypes,
	}.Build()
	File_cacheserver_v1_namespaced_proto = out.File
	file_cacheserver_v1_namespaced_proto_goTypes = nil
	file_cacheserver_v1_namespaced_proto_depIdxs = nil
}
