// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: cacheserver/v1/secret.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Expire        *durationpb.Duration   `protobuf:"bytes,3,opt,name=expire,proto3,oneof" json:"expire,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSecretRequest) Reset() {
	*x = SetSecretRequest{}
	mi := &file_cacheserver_v1_secret_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSecretRequest) ProtoMessage() {}

func (x *SetSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cacheserver_v1_secret_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSecretRequest.ProtoReflect.Descriptor instead.
func (*SetSecretRequest) Descriptor() ([]byte, []int) {
	return file_cacheserver_v1_secret_proto_rawDescGZIP(), []int{0}
}

func (x *SetSecretRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetSecretRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SetSecretRequest) GetExpire() *durationpb.Duration {
	if x != nil {
		return x.Expire
	}
	return nil
}

func (x *SetSecretRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type DelSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelSecretRequest) Reset() {
	*x = DelSecretRequest{}
	mi := &file_cacheserver_v1_secret_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelSecretRequest) ProtoMessage() {}

func (x *DelSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cacheserver_v1_secret_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelSecretRequest.ProtoReflect.Descriptor instead.
func (*DelSecretRequest) Descriptor() ([]byte, []int) {
	return file_cacheserver_v1_secret_proto_rawDescGZIP(), []int{1}
}

func (x *DelSecretRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretRequest) Reset() {
	*x = GetSecretRequest{}
	mi := &file_cacheserver_v1_secret_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretRequest) ProtoMessage() {}

func (x *GetSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cacheserver_v1_secret_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretRequest.ProtoReflect.Descriptor instead.
func (*GetSecretRequest) Descriptor() ([]byte, []int) {
	return file_cacheserver_v1_secret_proto_rawDescGZIP(), []int{2}
}

func (x *GetSecretRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SecretID      string                 `protobuf:"bytes,3,opt,name=secretID,proto3" json:"secretID,omitempty"`
	SecretKey     string                 `protobuf:"bytes,4,opt,name=secretKey,proto3" json:"secretKey,omitempty"`
	Expires       int64                  `protobuf:"varint,5,opt,name=expires,proto3" json:"expires,omitempty"`
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretResponse) Reset() {
	*x = GetSecretResponse{}
	mi := &file_cacheserver_v1_secret_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretResponse) ProtoMessage() {}

func (x *GetSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cacheserver_v1_secret_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretResponse.ProtoReflect.Descriptor instead.
func (*GetSecretResponse) Descriptor() ([]byte, []int) {
	return file_cacheserver_v1_secret_proto_rawDescGZIP(), []int{3}
}

func (x *GetSecretResponse) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *GetSecretResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetSecretResponse) GetSecretID() string {
	if x != nil {
		return x.SecretID
	}
	return ""
}

func (x *GetSecretResponse) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

func (x *GetSecretResponse) GetExpires() int64 {
	if x != nil {
		return x.Expires
	}
	return 0
}

func (x *GetSecretResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetSecretResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetSecretResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetSecretResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_cacheserver_v1_secret_proto protoreflect.FileDescriptor

const file_cacheserver_v1_secret_proto_rawDesc = "" +
	"\n" +
	"\x1bcacheserver/v1/secret.proto\x12\x0ecacheserver.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9d\x01\n" +
	"\x10SetSecretRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x126\n" +
	"\x06expire\x18\x03 \x01(\v2\x19.google.protobuf.DurationH\x00R\x06expire\x88\x01\x01\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescriptionB\t\n" +
	"\a_expire\"$\n" +
	"\x10DelSecretRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"$\n" +
	"\x10GetSecretRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"\xc1\x02\n" +
	"\x11GetSecretResponse\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bsecretID\x18\x03 \x01(\tR\bsecretID\x12\x1c\n" +
	"\tsecretKey\x18\x04 \x01(\tR\tsecretKey\x12\x18\n" +
	"\aexpires\x18\x05 \x01(\x03R\aexpires\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x128\n" +
	"\tcreatedAt\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x128\n" +
	"\tupdatedAt\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB#Z!cacheserver/api/cacheserver/v1;v1b\x06proto3"

var (
	file_cacheserver_v1_secret_proto_rawDescOnce sync.Once
	file_cacheserver_v1_secret_proto_rawDescData []byte
)

func file_cacheserver_v1_secret_proto_rawDescGZIP() []byte {
	file_cacheserver_v1_secret_proto_rawDescOnce.Do(func() {
		file_cacheserver_v1_secret_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cacheserver_v1_secret_proto_rawDesc), len(file_cacheserver_v1_secret_proto_rawDesc)))
	})
	return file_cacheserver_v1_secret_proto_rawDescData
}

var file_cacheserver_v1_secret_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_cacheserver_v1_secret_proto_goTypes = []any{
	(*SetSecretRequest)(nil),      // 0: cacheserver.v1.SetSecretRequest
	(*DelSecretRequest)(nil),      // 1: cacheserver.v1.DelSecretRequest
	(*GetSecretRequest)(nil),      // 2: cacheserver.v1.GetSecretRequest
	(*GetSecretResponse)(nil),     // 3: cacheserver.v1.GetSecretResponse
	(*durationpb.Duration)(nil),   // 4: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_cacheserver_v1_secret_proto_depIdxs = []int32{
	4, // 0: cacheserver.v1.SetSecretRequest.expire:type_name -> google.protobuf.Duration
	5, // 1: cacheserver.v1.GetSecretResponse.createdAt:type_name -> google.protobuf.Timestamp
	5, // 2: cacheserver.v1.GetSecretResponse.updatedAt:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_cacheserver_v1_secret_proto_init() }
func file_cacheserver_v1_secret_proto_init() {
	if File_cacheserver_v1_secret_proto != nil {
		return
	}
	file_cacheserver_v1_secret_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cacheserver_v1_secret_proto_rawDesc), len(file_cacheserver_v1_secret_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cacheserver_v1_secret_proto_goTypes,
		DependencyIndexes: file_cacheserver_v1_secret_proto_depIdxs,
		MessageInfos:      file_cacheserver_v1_secret_proto_msgTypes,
	}.Build()
	File_cacheserver_v1_secret_proto = out.File
	file_cacheserver_v1_secret_proto_goTypes = nil
	file_cacheserver_v1_secret_proto_depIdxs = nil
}
